const randomstring = require("randomstring");
const {sequelize} = require("../database");
const { Sequelize, Model, DataTypes } = require('sequelize');
class Scooter extends Model {}

Scooter.init({
    imei: { type: DataTypes.STRING, unique: true },
    qr: { type: DataTypes.STRING, unique: true } // TODO you can make this autogenerated
}, {
    sequelize,
    modelName: 'scooters',
    hooks: {
        beforeValidate: (scooter, options) => {
            scooter.qr = randomstring.generate(7);
        }
    },
});

module.exports = Scooter;
